"""JWT authentication middleware for FastAPI.

This module provides JWT token validation and user authentication for protected endpoints.
It validates tokens generated by the Next.js frontend and extracts user identity.
"""

from jose import jwt, JWTError, ExpiredSignatureError
from fastapi import HTTPException, Security, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from typing import Optional
from config import settings


# HTTP Bearer security scheme for FastAPI
security = HTTPBearer()


class AuthMiddleware:
    """JWT authentication middleware for validating user tokens.
    
    This middleware validates JWT tokens from the Authorization header,
    verifies their signature using the shared JWT_SECRET, and extracts
    the user ID for use in protected endpoints.
    """
    
    def __init__(self, jwt_secret: str):
        """Initialize the authentication middleware.
        
        Args:
            jwt_secret: Secret key used to verify JWT signatures
        """
        self.jwt_secret = jwt_secret
    
    async def get_current_user(
        self, 
        credentials: HTTPAuthorizationCredentials = Security(security)
    ) -> str:
        """Extract and validate JWT token, returning the authenticated user ID.
        
        This dependency can be used in FastAPI route handlers to require authentication.
        It extracts the JWT token from the Authorization header, validates it, and
        returns the user ID from the token payload.
        
        Args:
            credentials: HTTP Bearer credentials from the Authorization header
            
        Returns:
            str: The authenticated user's ID (userId from token payload)
            
        Raises:
            HTTPException: 401 if token is missing, invalid, expired, or malformed
        """
        if not credentials:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Authorization header missing"
            )
        
        token = credentials.credentials
        
        if not token:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Token missing"
            )
        
        try:
            # Decode and verify the JWT token
            payload = jwt.decode(
                token, 
                self.jwt_secret, 
                algorithms=["HS256"]
            )
            
            # Extract userId from payload
            user_id: Optional[str] = payload.get("userId")
            
            if user_id is None:
                raise HTTPException(
                    status_code=status.HTTP_401_UNAUTHORIZED,
                    detail="Invalid token: missing userId"
                )
            
            return user_id
            
        except HTTPException:
            # Re-raise HTTPExceptions (like missing userId)
            raise
        except ExpiredSignatureError:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Token has expired"
            )
        except JWTError:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid token"
            )
        except Exception as e:
            # Catch any other unexpected errors
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Authentication failed"
            )


# Global auth middleware instance
auth_middleware = AuthMiddleware(jwt_secret=settings.jwt_secret)
